### ISSUE TITLE
Code for Chapter 2 SMA-Signal results in error [ERRNO] No such file or Directory; 'APPL'

### ISSUE THREAD

**Issue by CarterFitz** [PacktPublishing/Python-for-Finance-Cookbook#1] opened 2020-03-18 15:08 UTC
I am on a Windows unit.  When I run the code from page 52 in Jupyter Notebook I get the error "No such file or directory".  I am using the following Packages:
Python==3.7.6
Anaconda Navigator==1.9.12
Backtrader==1.9.74.123
Cufflinks==0.17.3
Notebook==6.0.3
Numpy==1.18.1
Pandas==1.0.1
YFinance==0.1.54
[BT Signal.pdf](https://github.com/PacktPublishing/Python-for-Finance-Cookbook/files/4349673/BT.Signal.pdf)

**Comment by erykml** [comment] 2020-03-20 19:11
It seems that there is some issue with the Yahoo Finance API within `backtrader` (for example, as reported [here](https://community.backtrader.com/topic/2353/is-yahoo-api-down-right-now-cannot-get-any-data-feed-through-function) or [here](https://community.backtrader.com/topic/2353/is-yahoo-api-down-right-now-cannot-get-any-data-feed-through-function/2)). A possible workaround is to use either CSV input or load data straight from a `pd.DataFrame`. For information on how to use these two approaches, you can refer to [the source code](https://github.com/mementum/backtrader/tree/master/backtrader/feeds). While using the latter one, you can import data directly to a `pd.DataFrame` by using the approach presented in Chapter 1.

**Comment by CarterFitz** [comment] 2020-03-20 19:23
Eryk,
Thank you for the quick response.  With the virus outbreak I am working
from home and really wanted to make some progress with this book and your
code.  I will try one of the other approaches.

I guess others must be having the same issue?  I will keep checking the
github site for any further updates.
Carter

**Comment by erykml** [comment] 2020-03-20 20:04
Hi Carter, 

I added an extra [Notebook](https://github.com/PacktPublishing/Python-for-Finance-Cookbook/blob/master/Chapter%2002/pandas_datafeed_example.ipynb) with a workaround. It is quite simple and can be applied to all the other recipes using `backtrader`. I do hope it will help you and others while the issue is not fixed (if it will be fixed).

Cheers, 
Eryk

**Closed as completed** 2020-03-21 22:10 UTC
Labels: help wanted
