### ISSUE TITLE
performance_evaluation_report(learn) wont' run

### ISSUE THREAD

**Issue by JeremyWhittaker** [PacktPublishing/Python-for-Finance-Cookbook#8] opened 2020-09-23 00:13 UTC
Trying to run this code from chapter 10 and receiving and error. 

`performance_evaluation_report(learn)`

```
AttributeError                            Traceback (most recent call last)
<ipython-input-28-8b0585476687> in <module>()
----> 1 performance_evaluation_report(learn)

<ipython-input-6-a6983da9cfee> in performance_evaluation_report(model, show_plot, labels, show_pr_curve)
     35     y_pred_prob = preds_valid.numpy()[:, 1]
     36 
---> 37     cm = metrics.confusion_matrix(y_test, y_pred)
     38     tn, fp, fn, tp = cm.ravel()
     39 

AttributeError: module 'fastai.metrics' has no attribute 'confusion_matrix'
```

**Comment by erykml** [comment] 2020-10-05 07:35
Hi @N2Network,

Apologies for the late reply. Most likely this issue is caused by the fact that when I was writing the book, I was using version `1.x` of the `fastai` library, while now the current one is `2.x`. Could you please install the previous version of the library and try again?

Hope this solves your problem :)

**Comment by sohamapackt** [comment] 2020-10-15 06:19
Hi,

I am closing this issue. 
In case the issue still persists, feel free to open it again.

Thanks!

**Closed as completed by sohamapackt** 2020-10-15 06:19 UTC
